<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobTitleSeeder extends Seeder
{
    public function run(): void
    {
        $jobTitles = [
            'DRIVER',
            'GADGET SPECIALIST LEADER (WJ1)',
            'MT WAREHOUSE STAFF',
            'MT FINANCE STAFF E-COMMERCE',
            'AREA SALES COORDINATOR REALME',
            'ADMIN PROGRAM',
            'SALES ASSOCIATE',
            'STAFF ADMIN LOGISTIK',
            'MT SALES TECNO',
            'STAFF WAREHOUSE',
            'OFFICE BOY',
            'STAFF AR',
            'CUSTOMER SERVICE',
            'GADGET SPECIALIST (WJ2)',
            'MT SALES ZTE',
            'HEAD STORE (CJ1)',
            'TUKANG KEMASAN',
            'CHIEF SALES OFFICER',
            'LEGAL COORDINATOR',
            'GADGET SPECIALIST (WJ1)',
            'HEAD STORE (WJ1)',
            'LEADER SHOWROOM',
            'Management Trainee Production',
            'MT - AREA SALES MANAGER ZTE',
            'TELEMARKETING BIG 1',
            'SECURITY',
            'CHIEF INTERNAL AUDIT',
            'RELATIONSHIP OFFICER',
            'STAFF INTERNAL AUDIT MKLI',
            'MT TAX SUPERVISOR',
            'DESIGN GRAFIS MKLI',
            'AUDIT STOCK OPNAME & VISIBILITY',
            'MT SUPPLY CHAIN & TRANSLATOR',
            'KEPALA GUDANG',
            'DRIVER LOGISTIK',
            'AREA SALES MANAGER REALME',
            'CSO & COO',
            'STAFF PAJAK',
            'PJS MANAGER HUMAN CAPITAL AFILIASI',
            'MT AR',
            'STAFF FINANCE EDC',
            'GADGET SPECIALIST (CJ1)',
            'PERSONALIA MKLI & RISM',
            'WEB DEVELOPMENT',
            'ADMIN RETUR',
            'COORDINATOR WAREHOUSE DAN LOGISTIK',
            'SPV FINANCE ACCOUNTING',
            'GADGET SPECIALIST LEADER (WJ2)',
            'BUSINESS DEVELOPMENT COORDINATOR',
            'MT ADMIN PROSES ONLINE',
            'HR SUPERVISOR',
            'DATA ANALYST COORDINATOR',
            'Crew Store',
            'ADMIN GROSIR LEADER',
            'KASIR',
            'MT KURIR',
            'TALENT ACQUISITION OFFICER',
            'STAFF KAS BESAR',
            'AREA MANAGER',
            'IT Support Helpdesk & Networking',
            'STAFF PURCHASING (1)',
            'HEAD STORE AMAZY',
            'TEAM LEADER PEMBELIAN',
            'MT ADMIN E-COMMERCE',
            'PERSONNEL COORDINATOR',
            'STAFF FINANCE TRANSFER',
            'BOARD OF DIRECTOR',
            'MANAGER OPERASIONAL',
            'TELEMARKETING BIG 3',
            'AR COORDINATOR',
            'DRIVER MKLI',
            'TELEMARKETING BIG 2',
            'MT WAREHOUSE LEADER ONLINE',
            'GADGET SPECIALIST (WJ3)',
            'DESIGN GRAFIS',
            'KURIR',
            'STAFF ACCOUNTING',
            'RETAIL STORE COORDINATOR (WJ3)',
            'SUPPLY CHAIN MANAGER',
            'COOK',
            'HUMAN CAPITAL MANAGER RISM & MKLI',
            'SECRETARY OF CEO',
            'STAFF CHECKER',
            'APPRAISAL',
            'STAFF ACCOUNTING RESTO',
            'SALES ORAIMO WJ',
            'CHIEF OPERATIONAL OFFICER',
            'TALENT ACQUISITION OFFICER MKLI',
            'RETAIL STORE COORDINATOR (WJ1)',
            'DIGITAL MARKETING LEADER',
            'HANDPHONE ENGINEER',
            'SENIOR ACCOUNTING STAFF MKLI',
            'ADMIN DATA SUPPORT ZTE',
            'CS MARKETPLACE',
            'GADGET SPECIALIST LEADER (CJ1)',
            'STAFF FINANCE TRANSFER MKLI RISM',
            'LEADER RETUR',
            'GENERAL AFFAIR OFFICER',
            'STAFF AR RISM',
            'MT SUPPLY CHAIN OFFICER',
            'MT STAFF INTERNAL AUDIT',
            'HEAD STORE (WJ2)',
            'STAFF RETAIL STORE',
            'STAFF PAJAK MKLI RISM',
            'STAFF PURCHASING ONLINE',
            'PERSONNEL OFFICER',
            'FINANCE AUDIT COORDINATOR',
            'LEADER IT SUPPORT',
            'MT - STAFF FINANCE KAS',
            'GOLDSMITH',
            'CUSTOMER SERVICE MARKET PLACE',
            'AUDIT COORDINATOR',
            'KEPALA TEKNISI',
            'STAFF RETUR',
            'IT Support Mobile & CCTV',
            'ADMIN COD',
            'CONTENT CREATOR',
            'MT SUPERVISOR SALES TECNO',
            'PURCHASE & LOGISTIC COORDINATOR',
            'GENERAL AFFAIR ENGINEER',
            'ADMIN DATA SUPPORT TECNO',
            'Data Analyst',
            'FIELD INTERNAL AUDIT MKLI',
            'COORDINATOR FINANCE',
            'TEAM LEADER ACCOUNTING',
            'MT HEAD STORE',
            'LEADER REFUND & PROGRAM',
            'AUDIT FIELD TEAM LEADER',
            'ACCOUNT PAYABLE RISM & MKLI',
            'GADGET SPECIALIST (WJ4)',
            'MANAGER RETAIL AUTO EV',
            'SALES AREA ITEL REALME',
            'ORGANIZATION DEVELOPMENT',
            'GENERAL AFFAIR MKLI',
            'ADMIN PEMBELIAN',
            'DESIGN CREATOR',
            'GENERAL MANAGER ZTE',
            'CASHIER OFFICER (WJ4)',
            'RETAIL STORE COORDINATOR (CJ1)',
            'TEAM LEADER OFFLINE',
            'IT Support Afiliasi',
            'STAFF INTERNAL AUDIT',
            'BUSINESS DEVELOPMENT LEADER',
            'STAFF PURCHASING (2)',
            'ADMIN SOCMED',
            'STAFF KPI',
            'KEPALA GUDANG AKSESORIS',
            'IT SUPPORT COORDINATOR',
            'GADGET SPECIALIST LEADER (WJ3)',
            'SUPERVISOR E-COMMERCE',
            'GENERAL AFFAIR COORDINATOR',
            'FINANCE & ACCOUNTING MANAGER',
            'RETAIL STORE COORDINATOR (WJ2)',
            'Asst. Sales Manager',
            'LEADER WAREHOUSE DAN LOGISTIK',
            'RETAIL STORE MANAGER',
            'FINANCE ACCOUNTING TAX MANAGER',
        ];

        $timestamp = Carbon::now();

        $jobTitlesData = array_map(function ($title) use ($timestamp) {
            return [
                'title' => $title,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ];
        }, $jobTitles);

        DB::table('job_titles')->insert($jobTitlesData);
    }
}
